### ISSUE TITLE
transcriptor er feil veg

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sme#15]
```sh
echo 33 | hfst-lookup -q src/transcriptions/transcriptor-numbers-digit2text.filtered.lookup.hfstol 
33	33+?

echo 33 | hfst-lookup -q src/transcriptions/transcriptor-numbers-text2digit.filtered.lookup.hfstol 
33	golbmalogigolbma
```

Altså: `text2digit` oppfører seg som `digit2text`, og omvendt. Dette gjer at tekstnormalisering/ekspandering i tekst-til-taleprosesseringa ikkje fungerer.

Eg set både Lene og Thomas på denne, og kanskje @carges òg må sjå på saka pga den bruken desse filene har i Oahpa. @Trondtr har du sysnpunkt? Du var med og laga desse filene.

**Comment by rueter** [comment]
It looks like some how or other the file
lang-sme/src/transcriptions/transcriptor-numbers-digit2text.lexc

has the ordering TEXT : DIGIT, something we fixed in the AKU projects about
4 years ago.

LEXICON ONESG
miljárda:1   OVERMILLIONS ;
guokte:2     GIGA ;
golbma:3     GIGA ;
njeallje:4   GIGA ;
vihtta:5     GIGA ;
guhtta:6     GIGA ;
čieža:7      GIGA ;
gávcci:8     GIGA ;
ovcci:9      GIGA ;

THIS also looks one-sided:
LEXICON SMALLDATEDAYMARK
:@U.DATE.1@1 DATEMONTHSEPARATOR ;
:@U.DATE.2@2 DATEMONTHSEPARATOR ;
:@U.DATE.3@3 DATEMONTHSEPARATOR ;
:@U.DATE.4@4 DATEMONTHSEPARATOR ;
:@U.DATE.5@5 DATEMONTHSEPARATOR ;
:@U.DATE.6@6 DATEMONTHSEPARATOR ;
:@U.DATE.7@7 DATEMONTHSEPARATOR ;
:@U.DATE.8@8 DATEMONTHSEPARATOR ;
:@U.DATE.9@9 DATEMONTHSEPARATOR ;

Jaska

**Comment by snomos** [comment]
Denne hastar. @Trondtr kan du sjå på dette?

**Comment by Trondtr** [comment]
Kva er det som gjer at dette hastar no? Vi vil at språka skal vere konsistent, men dei er det ikkje, og det står på todo-lista å gjer dei det.

**Comment by Trondtr** [comment]
aha, ok, pga tekst-til-tale. Eg har førelesing til 1500 men skal sjå på dette etterpå. Er det travlare må nokon annan gjere det.

**Comment by snomos** [comment]
Denne er fiksa for SME. Eg stengjer.
