### ISSUE TITLE
No analysis for "Ergonomalaš"

### ISSUE THREAD

**Issue by carges** [giellalt/lang-sme#23]
I get no analysis for "Ergonomalaš" both at the beginning of sentence and alone:
````
echo 'Ergonomalaš ja sosiála vuhtiiváldimat, mátkkoštangaska jna.'| hfst-tokenise --print-all --giella-cg --no-weights --unique tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 --grammar tools/tokenisers/mwe-dis.bin | cg-mwesplit | vislcg3 --grammar src/cg3/disambiguator.bin | vislcg3 --grammar src/cg3/korp.bin | vislcg3 --grammar src/cg3/dependency.bin
:Ergonomalaš 
"<ja>"
	"ja" CC @CVP #1->3
: 
"<sosiála>"
	"sosiála" A Sem/Dummytag Attr @>N #2->3
: 
"<vuhtiiváldimat>"
	"vuhtiiváldin" N Sem/Act Pl Nom @HNOUN #3->0
"<,>"
	"," CLB #4->3
: mátkkoštangaska 
"<jna.>"
	"jna" Adv ABBR Gram/IAbbr @X #5->0
:\n
````
same here:
````
echo 'Ergonomalaš'| hfst-tokenise --print-all --giella-cg --no-weights --unique tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 --grammar tools/tokenisers/mwe-dis.bin | cg-mwesplit | vislcg3 --grammar src/cg3/disambiguator.bin | vislcg3 --grammar src/cg3/korp.bin | vislcg3 --grammar src/cg3/dependency.bin
:Ergonomalaš\n
````

**Comment by snomos** [comment]
This is most likely because the `š ` in `Ergonomalaš` is encoded as a two-character sequence: `s` + ``, as seen in this screenshot from UnicodeChecker:

<img width="352" alt="Skjermbilde 2021-06-28 kl  16 51 17" src="https://user-images.githubusercontent.com/1255285/123647806-15763e80-d831-11eb-992c-bb4d8225683f.png">

 The strange thing is that this type of decomposed diacritics should be covered/supported by our descriptive analysers, including the one you are using. So something is amiss somewhere. Start by having a look at the spellrelax files in `src/orthography/`, to check that `š` is included in the sets there.

**Comment by snomos** [comment]
Test result:

```sh
echo 'Ergonomalaš ja sosiála vuhtiiváldimat, mátkkoštangaska jna.'| hfst-tokenise --print-all --giella-cg --no-weights --unique tools/tokenisers/tokeniser-gramcheck-gt-desc.pmhfst | vislcg3 --grammar tools/tokenisers/mwe-dis.bin | cg-mwesplit | vislcg3 --grammar src/cg3/disambiguator.bin | vislcg3 --grammar src/cg3/korp.bin | vislcg3 --grammar src/cg3/dependency.bin
"<Ergonomalaš>"
	"Ergonomalaš" ? @X #1->0
: 
"<ja>"
	"ja" CC @CNP #2->1
: 
"<sosiála>"
	"sosiála" A Sem/Dummytag Attr @>N #3->4
: 
"<vuhtiiváldimat>"
	"vuhtiiváldin" N Sem/Act Pl Nom @HNOUN #4->0
"<,>"
	"," CLB #5->4
: 
"<mátkkoštangaska>"
	"mátkkoštangaska" ? @X #6->0
: 
"<jna.>"
	"jna" Adv ABBR Gram/IAbbr @X #7->0
:\n
```

The word is unknown, but at least it is now recognised 😃

**Comment by Trondtr** [comment]
The š is solved (thanks to Sjur!), but I reopen, since the problem is more general (or we may move it to a more general bug).

Sjur added these diacritics {̌}|{́}|{̃} (caron, acute accent, tilde) for sme. 

Looking across the languages, we see that no language have these in the respective files, except mhr, who has more:

|{́}
|{̈}
|{̌}
|{̶}
|{ϸ}
|{֪}
|{ٕ}

The reason for this is that I have included a 65 mill word corpus from pdfs, and simply included all characters I found (the 7 quoted are thus a subset). This gives two questions:

a. Should the repertoire of symbols in the two sme files be enlarged, and if so, how much?
b. Should the same list be layd out to the .pmscript files for all languages, or should they be adjusted to each language's need?

As for (a), I would say "yes". The sme file is still missing the combining diaeresis, U-0308. A minimum would thus be that sme should contain the (potentially) combining deaereses of sme itself (done, now, fine!) and of the majority languages: U+0308, 030A, perhaps also more exotic like 0303 tilde (added by Sjur now).

As for (b), it is obvious that each language would need its relevant characters in its .pmscript files. For maintenance reason, the "full pack fits them all" would be optimal. One factor influencing the answer to question (b) is whether there are any disadvantage of having a very long list in the file (as mhr has).

**Comment by snomos** [comment]
This bug is solved:

```shell
echo 'Ergonomalaš ja sosiála vuhtiiváldimat, mátkkoštangaska jna.'| \
hfst-tokenise --print-all --giella-cg --no-weights --unique \
  tools/tokenisers/tokeniser-gramcheck-gt-desc.pmhfst | \
vislcg3 --grammar tools/tokenisers/mwe-dis.bin | \
cg-mwesplit | \
vislcg3 --grammar src/cg3/disambiguator.bin | \
vislcg3 --grammar src/cg3/korp.bin | \
vislcg3 --grammar src/cg3/dependency.bin

"<Ergonomalaš>"
	"ergonomalaš" A Sem/Dummytag Attr @>N #1->4
: 
"<ja>"
	"ja" CC @CNP #2->1
: 
"<sosiála>"
	"sosiála" A Sem/Dummytag Attr @>N #3->1
: 
"<vuhtiiváldimat>"
	"vuhtiiváldin" N Sem/Act Pl Nom @HNOUN #4->0
"<,>"
	"," CLB #5->6
: 
"<mátkkoštangaska>"
	"gaska" N Sem/Feat-measr_Plc Sg Nom <cohort-with-dynamic-compound> <cohort-with-dynamic-compound> @APP-N< #6->4
		"mátkkoštit" Ex/V IV Gram/3syll Der/NomAct N Sem/Act Cmp/SgNom Cmp #6->4
: 
"<jna.>"
	"jna" Adv ABBR Gram/IAbbr @X #7->0
:\n
```

It is solved by two independent additions:
- the pmscript files for all languages have all combining diacritics defined as part of the unknown alphabet
- @flammie has implemented automatic conversion to and from pre- and decomposed letters in descriptive FST's

Taken together this means that in cases like this one, the precomposed `š` in `ergonomalaš` is optionally and automatically converted to a decomposed alternative, to allow for analysis of such cases. In addition unknown words with decomposed diacritics will be handled gracefully by the tokeniser.
