### ISSUE TITLE
tools/mt/apertium missing semsets.cg3

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-sme#5]
````
grep -v '#RemoveFromApertium' < ../../../src/cg3/disambiguator.cg3 > disambiguator-mt-gt.cg3
"/usr/bin/cg-comp" disambiguator-mt-gt.cg3 disambiguator-mt-gt.bin
disambiguator-mt-gt.cg3: Error: Cannot stat semsets.cg3 due to error -1 - bailing out!
````

Needs to copy in `semsets.cg3`, or adjust the include directive, or do the work in the src/cg3 folder.

**Comment by snomos** [comment]
@Trondtr or @leneantonsen could you have a look? This bug is blocking nightly builds.

**Comment by Trondtr** [comment]
I need some more context here. The semset.cg3 file seems ok, wrt. syntax. The error message in the quoted logfile is:

**Comment by Trondtr** [comment]
disambiguator-mt-gt.cg3: Error: Cannot stat semsets.cg3 due to error -1 - bailing out!
make[5]: *** [Makefile:1436: disambiguator-mt-gt.bin] Error 1

... and it is not enough informative for me to be able to reproduce.

When I try to compile I get a totally different error:
     98548 Abort trap: 6           | /usr/local/bin/hfst-xfst -p -v --format=foma
make[2]: *** [analyser-gt-norm.tmp.hfst] Error 134
make[1]: *** [all-recursive] Error 1

libc++abi.dylib: terminating with uncaught exception of type TransducerTypeMismatchException

aha, I remember this one from Sjur: make clean && make. This will take some time.

**Comment by TinoDidriksen** [comment]
The build uses configure flags `--without-forrest --with-hfst --enable-tokenisers --without-xfst --enable-reversed-intersect --enable-spellers --enable-hfst-mobile-speller --enable-alignment --disable-minimised-spellers --enable-syntax --enable-analysers --enable-generators --enable-apertium --enable-grammarchecker --with-backend-format=foma --enable-dicts --enable-oahpa --enable-morpher --disable-hfst-desktop-spellers` where I think the important one for this error is `--enable-apertium`

**Comment by snomos** [comment]
@Trondtr - @unhammer arbeider med saka. Jf diskusjonen her: https://giella.zulipchat.com/#narrow/stream/124552-sme/topic/cg3-stat-feil
